[tool.black]
line-length =88arget-version =py310]
include = '\.pyi?$
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
ool.isort]
profile = black
multi_line_output = 3
line_length = 88
known_first_party = [app"]
known_third_party = ["fastapi", "uvicorn,langchain,pydantic"]

[tool.mypy]
python_version = 3.10
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true

[[tool.mypy.overrides]]
module =    langchain.*",
    pymongo.*,   pymilvus.*,
 psycopg2.*
]
ignore_missing_imports = true

[tool.bandit]
exclude_dirs = ["tests",venv", ".venv"]
skips =B101,B601 