apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus
  template:
    metadata:
      labels:
        app: milvus
    spec:
      containers:
        - name: milvus
          image: milvusdb/milvus:v2.3.9
          ports:
            - containerPort: 19530
            - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: milvus
spec:
  type: ClusterIP
  selector:
    app: milvus
  ports:
    - port: 19530
      targetPort: 19530
    - port: 9091
      targetPort: 9091 